Repository hmcts/probate-submit-service, pull requests merged in 2019-02, with the labels that each got.

#122 Java update
  Dockerfile
Labels: ns:probate-submit-service-pr-122

#124 adding new java image
  Dockerfile
Labels: ns:probate-submit-service-pr-124

#128 Pro 4152 update v2 submissions call for allocation of registry
  build.gradle
  docker/docker-compose-with-ccd-pa.yml
  src/main/java/uk/gov/hmcts/probate/services/submit/core/CaseTypeConfiguration.java
  src/main/java/uk/gov/hmcts/probate/services/submit/core/proccessors/impl/CreateCaseSubmissionsProcessor.java
  src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
  src/main/java/uk/gov/hmcts/probate/services/submit/validation/validator/CaveatValidator.java
  src/test/java/uk/gov/hmcts/probate/services/submit/core/CreateCaseSubmissionsProcessorTest.java
  src/test/java/uk/gov/hmcts/probate/services/submit/validation/validator/CaveatValidatorTest.java
Labels: ns:probate-submit-service-pr-128
