Repository hmcts/probate-submit-service, pull requests merged in 2019-10, with the labels that each got.

#221 upgrade jackson version
  Dockerfile
  build.gradle
  web.config
Labels: ns:probate-submit-service-pr-221

#227 Added app insights
  Dockerfile
  Jenkinsfile_CNP
  charts/probate-submit-service/Chart.yaml
  charts/probate-submit-service/requirements.yaml
  src/main/java/uk/gov/hmcts/probate/insights/AppInsights.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
Labels: ns:probate-submit-service-pr-227

#228 ASE To AKS Migration
  Jenkinsfile_CNP
Labels: ns:probate-submit-service-pr-228

#242 bump health starter
  build.gradle
Labels: ns:probate-submit-service-pr-242
