Repository hmcts/probate-submit-service, pull requests merged in 2020-10, with the labels that each got.

#372 DTSPB-685 Terraform and azure version upgrade
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-372

#373 DTSPB-631 changes for owasp version upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-373

#377 DTSPB-786: upgraded ccd client api
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-377
