Repository hmcts/probate-submit-service, pull requests merged in 2020-08, with the labels that each got.

#352 PRO-7904: Add gradle 5 to wrapper
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-352

#353 PRO-7812 Java11 upgrade changes
  .travis.yml
  Dockerfile
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-353

#359 PRO-7826 Fix Serenity report display
  README.md
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-359
