Repository hmcts/probate-submit-service, pull requests merged in 2021-11, with the labels that each got.

#572 Commons changes for will and codicils condition
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-572

#573 Dtspb 2454 ee first page
  build.gradle
  src/functionalTest/resources/application.properties
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-573

#574 Suppress depdendency warning
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-574

#575 DTSPB-2482: Legal statement change for excepted estate
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-575
