Repository hmcts/probate-submit-service, pull requests merged in 2021-12, with the labels that each got.

#576 DTSPB-2493: Make ihtFormCompletedOnline optional
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-576

#577 DTSPB-2516 specify log4j version in dependencies
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-577

#578 DTSPB-2523 Update log4j version for dependencies to 2.16.0
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-578
