Repository hmcts/probate-submit-service, pull requests merged in 2021-06, with the labels that each got.

#507 DTSPB-2020 Sync All env to master with every commit
  Jenkinsfile_CNP
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-507

#452 Pact tests submit service
  .gitignore
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
  src/contractTest/resources/application.properties
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesControllerProviderTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/ControllerProviderTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/SubmissionsControllerProviderTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/AbstractProbateSubmitServicePact.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/GetCaseConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/StartEventForCaseworkerConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/StartEventForCitizenConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/StartForCaseWorkerConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/StartForCitizenConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/SubmitEventForCaseworkerConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/SubmitEventForCitizenConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/SubmitForCaseworkerConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ccd/SubmitForCitizenConsumerTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/util/AssertionHelper.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/util/ObjectMapperTestUtil.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/util/PactDslFixtureHelper.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/util/ResourceLoader.java
  src/pactTest/resources/application.properties
  src/pactTest/resources/application.yml
  src/pactTest/resources/json/BaseStartJson.json
  src/pactTest/resources/json/GetCaseData.json
  src/pactTest/resources/json/StartEvent.json
  src/pactTest/resources/json/SubmitEventCitizen.json
  src/pactTest/resources/json/base-case.json
  src/pactTest/resources/json/caseWithExecsWelsh.json
  src/pactTest/resources/json/caseWithExecsWelsh1.json
  src/pactTest/resources/json/dsl-backoffice-case.json
  src/pactTest/resources/json/gop.multipleExecutors.full.json
  src/pactTest/resources/json/probate-casedata-map.json
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-452

#508 Fix the Probate-pact-commons library version and jitpack
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-508

#509 Fix CVE-2021-22118
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-509
