Repository hmcts/probate-submit-service, pull requests merged in 2021-05, with the labels that each got.

#483 Update glue config
  audit.json
  security.sh
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-483

#485 Update glue config
  audit.json
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-485

#488 fixing security scan issue
  security.sh
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-488

#503 Dtspb 1526 commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-503

#500 DTSPB-1946: added logging to determine nullPointer exceptions
  src/main/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImpl.java
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-500

#504 Rollback Commons version as lev not live yet
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-504
