Repository hmcts/probate-submit-service, pull requests merged in 2021-08, with the labels that each got.

#547 Fortify integration to nightly
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-547

#554 Suppress CVE until spring boot upgrade
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-554

#555 suppress CVE until spring boot upgrade
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-555

#552 DTSPB-2276 - Bump chart.yaml java version to 3.6.0
  charts/probate-submit-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-552

#557 New Tag for commons to fix TC issue
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-557
