Repository hmcts/probate-submit-service, pull requests merged in 2021-03, with the labels that each got.

#388 Dtspb 264 remove unused endpoints
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApi.java
  src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
  src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/PaymentsController.java
  src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/SubmissionsController.java
  src/main/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImpl.java
  src/main/java/uk/gov/hmcts/probate/services/submit/core/PaymentServiceImpl.java
  src/main/java/uk/gov/hmcts/probate/services/submit/services/CasesService.java
  src/main/java/uk/gov/hmcts/probate/services/submit/services/CoreCaseDataService.java
  src/main/java/uk/gov/hmcts/probate/services/submit/services/PaymentsService.java
  src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApiTest.java
  src/test/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesControllerTest.java
  src/test/java/uk/gov/hmcts/probate/services/submit/controllers/v2/PaymentsControllerTest.java
  src/test/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImplTest.java
  src/test/java/uk/gov/hmcts/probate/services/submit/core/PaymentServiceImplTest.java
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-388

#433 DTSPB-1647 Fix Bouncycastle dependency suppression
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-433

#440 DTSPB-1650+52 resolve suppressions for beanutils and httpclient
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-440

#442 DTSPB-1649 tomcat related suppressions resolution
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-442

#441 DTSPB-1686 Resolve CVE-2021-22112 suppression
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-441

#449 Resolve CVE-2020-1520 suppression
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-449
