Repository hmcts/probate-submit-service, pull requests merged in 2022-04, with the labels that each got.

#593 Dtspb 2704 springboot 2.6.6
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-593

#594 DTSPB-2689 remove Jackson databind from suppressions.xml
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-594

#597 DTSPB-2747 Fix CVE-2022-22968
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-597

#596 Dtspb 2544 pp notorial access
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-596
