Repository hmcts/probate-submit-service, pull requests merged in 2022-03, with the labels that each got.

#584 DTSPB-2642 Java chart version update
  charts/probate-submit-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-584

#585 DTSPB-2616 Fix Generating Serenity Report
  Jenkinsfile_CNP
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-585

#588 DTSPB-2645 Security Scan Fix
  security.sh
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-588

#591 DTSPB-699: bump commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-591

#592 DTSPB-1493 point to new commons version
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-592
