Repository hmcts/probate-submit-service, pull requests merged in 2022-12, with the labels that each got.

#636 DTSPB-2886-2800 updating probate commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-636

#641 Update Chart.yaml
  Jenkinsfile_CNP
  charts/probate-submit-service/Chart.yaml
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-641

#642 Update commons jar
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-642
