Repository hmcts/probate-submit-service, pull requests merged in 2022-05, with the labels that each got.

#595 Dtspb 247 resend notification after executor email changed
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-595

#600 DTSPB-2781: commons upgrade
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-600

#601 Autoscaling Update Chart.yaml
  charts/probate-submit-service/Chart.yaml
  charts/probate-submit-service/values.yaml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-601

#603 DTSPB-2799: Fix CVE-2016-1000027 Vulnerability For probate-submit-ser…
  charts/probate-submit-service/Chart.yaml
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-603

#602 DTSPB-2705 dob equals dod
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-602

#604 DTSPB-2081: resolved cve
  build.gradle
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-604

#598 DTSPB-2672: implementing Open ID Connect (OICD)
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-598
