Repository hmcts/probate-submit-service, pull requests merged in 2022-02, with the labels that each got.

#579 DTSPB-2584: Resolve the below deprecated warning form Java repos
  charts/probate-submit-service/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-579

#580 DTSPB-2586: fix cve vulnerabilities
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-580

#582 DTSPB-2604 fix the dependancy failure
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-582
