Repository hmcts/probate-submit-service, pull requests merged in 2022-10, with the labels that each got.

#625 DTSPB-3033 Supress CVE-2022-38752
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-625

#630 DTSPB-3039 Supress CVE-2022-42003,CVE-2022-42004
  suppressions.xml
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-630

#629 DTSPB-2997 hand off flag
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-629

#632 DTSPB-3100: remmoved s2s pact test
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ServiceAuthConsumerDetailTest.java
  src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/consumer/ServiceAuthConsumerLeaseTest.java
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-632

#626 DTSPB-2407-PA8A-and-DTSPB-2656-PA8B: update probate commons
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-626
