Repository hmcts/probate-submit-service, pull requests merged in 2023-06, with the labels that each got.

#694 Updating renovate config
  renovate.json
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-694

#685 DTSPB-3449 Update commons jar
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-685

#695 DTSPB-3617 address CVE-2023-20883
  build.gradle
Labels: ns:probate, prd:probate, rel:probate-submit-service-pr-695
